
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.17.116:3306/hls_base_all?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hzero
    password: hzero